#!/bin/sh

if [ "`stat -c %G /var/log/snorkel`" != 'nogroup' ]; then
    chown root.nogroup /var/log/snorkel
    chmod 775 /var/log/snorkel
fi

invoke-rc.d snorkel restart
invoke-rc.d snorkel.collector restart
