#!/bin/sh

PATH=$PATH:/usr/local/bin:/usr/bin:/bin
NODE_BIN=$(which nodejs||which node)

if [ ! -x "$NODE_BIN" ]; then
  echo "Can't find executable nodejs or node in PATH=$PATH"
  exit 1
fi

$NODE_BIN /opt/snorkel/collector.js 2>&1 >> /var/log/snorkel/collector.log

